/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/ico.glb --output ./src/components/3dmodel.jsx 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function SphereModel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/ico.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} />
      </group>
    </group>
  )
}

//useGLTF.preload('/ico.glb')
